Repository TheChance101/beep-beep, pull requests merged in 2023-10, with the labels that each got.

#478 Implement chat support screen with fake data
  client_end_user/shared/src/commonMain/kotlin/data/gateway/fake/FakeChatRemoteGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/mapper/Message.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/mapper/Ticket.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/mapper/Time.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/model/MessageDto.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/model/TicketDto.kt
  client_end_user/shared/src/commonMain/kotlin/di/GatewayModule.kt
  client_end_user/shared/src/commonMain/kotlin/di/UseCaseModule.kt
  client_end_user/shared/src/commonMain/kotlin/di/screenModelsModule.kt
  client_end_user/shared/src/commonMain/kotlin/domain/entity/Message.kt
  client_end_user/shared/src/commonMain/kotlin/domain/entity/Ticket.kt
  client_end_user/shared/src/commonMain/kotlin/domain/gateway/IChatGateway.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/GetTicketsUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/ManageMessagesUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/chatSupport/ChatSupportInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/chatSupport/ChatSupportScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/chatSupport/ChatSupportScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/chatSupport/ChatSupportUiEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/chatSupport/ChatSupportUiState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/chatSupport/composable/MessageCard.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreen.kt
  client_end_user/shared/src/commonMain/kotlin/resources/DrawableResources.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/IStringResources.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/Arabic.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicEG.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicIQ.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicPS.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicSY.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/en/English.kt
  client_end_user/shared/src/commonMain/resources/ic_send.xml
  client_end_user/shared/src/commonMain/resources/img_chat_placeholder.png
  design_system/shared/src/commonMain/kotlin/ui/composable/BpSimpleTextField.kt
Labels: feature, Backbone Team, Design

#484 dashboard/fix/snackbar_in_login
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/table/BpTable.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginUIState.kt
Labels: bug, Golden Team

#486 add shimmer effect to cuisines screen
  client_end_user/shared/src/commonMain/kotlin/presentation/cuisines/CuisinesScreen.kt
Labels: enhancement, Backbone Team

#405 Feature/add image cuisine
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/model/restaurant/CuisineDto.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/RestaurantService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/CuisineRoute.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/CuisineDto.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/CuisineCollection.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/mapper/CuisineMapper.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/entity/Cuisine.kt
Labels: Backbone Team

#487 end-user/refactor/profile-from-remote-api
  client_end_user/shared/src/commonMain/kotlin/data/gateway/fake/FakeRemoteGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/gateway/remote/UserRemoteRemoteGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/mapper/UserDetails.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/model/UserDetailsDto.kt
  client_end_user/shared/src/commonMain/kotlin/domain/gateway/IFakeRemoteGateway.kt
  client_end_user/shared/src/commonMain/kotlin/domain/gateway/IUserRemoteGateway.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/ManageUserUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/login/LoginScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registration/RegistrationScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registrationSubmit/RegistrationSubmitScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/profile/ProfileScreen.kt
Labels: enhancement, Backbone Team

#491 dashboard/feature/add_search_with_filter_user_endpoint
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/gateway/remote/UsersGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/getway/IUsersGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserScreenUiState.kt
Labels: feature, Golden Team

#494 Backend/feature/add restaurant name for meal
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/model/restaurant/MealDto.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/di/ApiClientModule.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/CuisineRoute.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/MealDto.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/mappers/MealMapper.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/mapper/MealMapper.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/relationModels/MealWithResturant.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/gateway/RestaurantGateway.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/gateway/RestaurantManagementGateway.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/entity/Meal.kt
Labels: feature, Backbone Team

#492 fix app icon and splash screen
  client_end_user/androidApp/src/androidMain/AndroidManifest.xml
  client_end_user/androidApp/src/androidMain/beep_beep_icon_launcher-playstore.png
  client_end_user/androidApp/src/androidMain/ic_launcher-playstore.png
  client_end_user/androidApp/src/androidMain/res/drawable-v24/ic_launcher_foreground.xml
  client_end_user/androidApp/src/androidMain/res/drawable/beep_beep_icon_launcher_foreground.xml
  client_end_user/androidApp/src/androidMain/res/drawable/ic_launcher_background.xml
  client_end_user/androidApp/src/androidMain/res/drawable/logo.xml
  client_end_user/androidApp/src/androidMain/res/mipmap-anydpi-v26/beep_beep_icon_launcher.xml
  client_end_user/androidApp/src/androidMain/res/mipmap-anydpi-v26/beep_beep_icon_launcher_round.xml
  client_end_user/androidApp/src/androidMain/res/mipmap-anydpi-v26/ic_launcher.xml
  client_end_user/androidApp/src/androidMain/res/mipmap-anydpi-v26/ic_launcher_round.xml
  client_end_user/androidApp/src/androidMain/res/mipmap-hdpi/beep_beep_icon_launcher.webp
  client_end_user/androidApp/src/androidMain/res/mipmap-hdpi/beep_beep_icon_launcher_round.webp
  client_end_user/androidApp/src/androidMain/res/mipmap-hdpi/ic_launcher.webp
  client_end_user/androidApp/src/androidMain/res/mipmap-hdpi/ic_launcher_foreground.webp
  client_end_user/androidApp/src/androidMain/res/mipmap-hdpi/ic_launcher_round.webp
  client_end_user/androidApp/src/androidMain/res/mipmap-mdpi/beep_beep_icon_launcher.webp
  client_end_user/androidApp/src/androidMain/res/mipmap-mdpi/beep_beep_icon_launcher_round.webp
  client_end_user/androidApp/src/androidMain/res/mipmap-mdpi/ic_launcher.webp
  client_end_user/androidApp/src/androidMain/res/mipmap-mdpi/ic_launcher_foreground.webp
  client_end_user/androidApp/src/androidMain/res/mipmap-mdpi/ic_launcher_round.webp
  client_end_user/androidApp/src/androidMain/res/mipmap-xhdpi/beep_beep_icon_launcher.webp
  client_end_user/androidApp/src/androidMain/res/mipmap-xhdpi/beep_beep_icon_launcher_round.webp
  client_end_user/androidApp/src/androidMain/res/mipmap-xhdpi/ic_launcher.webp
  client_end_user/androidApp/src/androidMain/res/mipmap-xhdpi/ic_launcher_foreground.webp
  client_end_user/androidApp/src/androidMain/res/mipmap-xhdpi/ic_launcher_round.webp
  client_end_user/androidApp/src/androidMain/res/mipmap-xxhdpi/beep_beep_icon_launcher.webp
  client_end_user/androidApp/src/androidMain/res/mipmap-xxhdpi/beep_beep_icon_launcher_round.webp
  client_end_user/androidApp/src/androidMain/res/mipmap-xxhdpi/ic_launcher.webp
  client_end_user/androidApp/src/androidMain/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  client_end_user/androidApp/src/androidMain/res/mipmap-xxhdpi/ic_launcher_round.webp
  client_end_user/androidApp/src/androidMain/res/mipmap-xxxhdpi/beep_beep_icon_launcher.webp
  client_end_user/androidApp/src/androidMain/res/mipmap-xxxhdpi/beep_beep_icon_launcher_round.webp
  client_end_user/androidApp/src/androidMain/res/mipmap-xxxhdpi/ic_launcher.webp
  client_end_user/androidApp/src/androidMain/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  client_end_user/androidApp/src/androidMain/res/mipmap-xxxhdpi/ic_launcher_round.webp
  client_end_user/androidApp/src/androidMain/res/values/beep_beep_icon_launcher_background.xml
  client_end_user/androidApp/src/androidMain/res/values/ic_launcher_background.xml
  client_end_user/androidApp/src/androidMain/res/values/splash.xml
  client_end_user/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  client_end_user/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/app-icon-1024.png
  client_end_user/iosApp/iosApp/Assets.xcassets/Primary.colorset/Contents.json
  client_end_user/iosApp/iosApp/Assets.xcassets/logobeep.imageset/120.png
  client_end_user/iosApp/iosApp/Assets.xcassets/logobeep.imageset/144.png
  client_end_user/iosApp/iosApp/Assets.xcassets/logobeep.imageset/152.png
  client_end_user/iosApp/iosApp/Assets.xcassets/logobeep.imageset/Contents.json
  client_end_user/iosApp/iosApp/Info.plist
Labels: feature, Backbone Team

#474 Delivery/feature/add map
  client_delivery/androidApp/src/androidMain/AndroidManifest.xml
  client_delivery/androidApp/src/androidMain/assets/bing_map/map/index.html
  client_delivery/androidApp/src/androidMain/assets/bing_map/map/script.js
  client_delivery/androidApp/src/androidMain/assets/bing_map/map/style.css
  client_delivery/androidApp/src/androidMain/kotlin/com/beepbeep/App.kt
  client_delivery/androidApp/src/androidMain/kotlin/com/beepbeep/MainActivity.kt
  client_delivery/androidApp/src/androidMain/kotlin/com/beepbeep/locationModule.kt
  client_delivery/iosApp/iosApp/Info.plist
  client_delivery/shared/build.gradle.kts
  client_delivery/shared/src/commonMain/kotlin/App.kt
  client_delivery/shared/src/commonMain/kotlin/data/gateway/local/LocationGateway.kt
  client_delivery/shared/src/commonMain/kotlin/di/GatewayModule.kt
  client_delivery/shared/src/commonMain/kotlin/di/UseCaseModule.kt
  client_delivery/shared/src/commonMain/kotlin/domain/entity/Location.kt
  client_delivery/shared/src/commonMain/kotlin/domain/gateway/local/ILocationGateway.kt
  client_delivery/shared/src/commonMain/kotlin/domain/usecase/ManageUserLocationUseCase.kt
  client_delivery/shared/src/commonMain/kotlin/domain/utils/ErrorType.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/base/BaseScreenModel.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/base/ErrorState.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/main/MainScreen.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/main/MainScreenModel.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/main/MainUiState.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/MapScreen.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/MapScreenModel.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/MapScreenUiState.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/MapUiMapper.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/composable/MapView.kt
  client_delivery/shared/src/iosMain/kotlin/Helper.kt
  gradle/libs.versions.toml
Labels: feature, Ruby Team

#479 Delivery app | save username in realm database
  client_delivery/shared/src/commonMain/kotlin/data/gateway/local/LocalConfigurationGateway.kt
  client_delivery/shared/src/commonMain/kotlin/data/local/model/UserConfigurationCollection.kt
  client_delivery/shared/src/commonMain/kotlin/domain/gateway/local/ILocalConfigurationGateway.kt
  client_delivery/shared/src/commonMain/kotlin/domain/usecase/ManageLoginUserUseCase.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/login/LoginScreenModel.kt
Labels: enhancement, Ruby Team

#443 End user/feature/search
  client_end_user/shared/src/commonMain/kotlin/data/gateway/fake/FakeRestaurantGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/gateway/remote/RestaurantGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/mapper/Explore.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/mapper/Meal.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/mapper/Restaurant.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/model/MealDto.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/model/MealRestaurantDto.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/model/RestaurntDto.kt
  client_end_user/shared/src/commonMain/kotlin/di/UseCaseModule.kt
  client_end_user/shared/src/commonMain/kotlin/di/screenModelsModule.kt
  client_end_user/shared/src/commonMain/kotlin/domain/entity/Explore.kt
  client_end_user/shared/src/commonMain/kotlin/domain/entity/Meal.kt
  client_end_user/shared/src/commonMain/kotlin/domain/entity/Restaurant.kt
  client_end_user/shared/src/commonMain/kotlin/domain/gateway/IRestaurantGateway.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/ManageFavouriteUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/SearchUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/mangeResturantUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/base/BaseScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/BottomSheet.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/MealBottomSheet.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/MealCard.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cuisines/CuisinesInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cuisines/CuisinesScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cuisines/CuisinesScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cuisines/CuisinesUiEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreenInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreenUiEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreenUiState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/composable/CuisineCard.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/meals/MealsInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/meals/MealsScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/meals/MealsScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/meals/MealsUiEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/meals/MealsUiState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/Composable/Chip.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/Composable/CloseButton.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/Composable/NeedToLoginSheet.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/Composable/ToastMessage.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/MealInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/RestaurantInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/RestaurantScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/RestaurantScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/resturantUIState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/search/SearchInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/search/SearchScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/search/SearchScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/search/SearchUiEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/search/SearchUiState.kt
Labels: feature, Backbone Team

#495 add loadig to login & sign up button
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/login/LoginScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registration/RegistrationScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registrationSubmit/RegistrationSubmitScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/profile/ProfileScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/profile/ProfileScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/profile/ProfileUIState.kt
Labels: Backbone Team

#503 refactor restaurant details
  client_end_user/shared/src/commonMain/kotlin/di/screenModelsModule.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/ManageFavouriteUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/BpImageCard.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/ItemSection.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeMappers.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreenInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreenUiEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreenUiState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/RestaurantScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/RestaurantScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/resturantUIState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/search/SearchScreen.kt
Labels: enhancement, Backbone Team

#501 dashboard/bug_fix/loading_restaurants
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantScreen.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/login/LoginScreen.kt
Labels: bug

#510 create and implement end point to get active trips for user
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/model/taxi/TripDto.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/RestaurantService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/TaxiService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/TaxiRoute.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/UserRoute.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/endpoints/OrderRoutes.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/mapper/MealMapper.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/gateway/RestaurantManagementGateway.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/gateway/IRestaurantManagementGateway.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/ManageOrderUseCase.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/dto/trip/TripDto.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/dto/trip/TripMappers.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/endpoints/TripRoutes.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/data/collection/TripCollection.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/data/collection/relationModel/TripWithTaxi.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/data/gateway/TaxiGateway.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/entity/Trip.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/gateway/ITaxiGateway.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/usecase/ClientTripsManagementUseCase.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/usecase/DriverTripsManagementUseCase.kt
Labels: enhancement, Backbone Team

#496 end-user/refactor/cart-screen
  client_end_user/shared/src/commonMain/kotlin/data/gateway/fake/FakeOrderGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/gateway/remote/TransactionsGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/mapper/Cart.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/mapper/Trip.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/model/CartDto.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/model/CartMealDto.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/model/TripDto.kt
  client_end_user/shared/src/commonMain/kotlin/di/GatewayModule.kt
  client_end_user/shared/src/commonMain/kotlin/domain/gateway/ITransactionsGateway.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/CartUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cart/CartMapper.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cart/CartScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cart/CartScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cart/CartUiState.kt
Labels: enhancement, Backbone Team

#428 Chat service/feature/chat messaging
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/ArabicLocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/EgyptLocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/EnglishLocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/IraqLocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/LocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/PalestineLocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/SyrainLocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/model/MessageDto.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/model/TicketDto.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/ChatService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/LocationService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/utils/ErrorHandler.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/utils/Extensions.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/di/ApiClientModule.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/ChatRoute.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/utils/ChatSocketHandler.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/plugins/Routing.kt
  service_chat/build.gradle.kts
  service_chat/gradle.properties
  service_chat/src/main/kotlin/org/thechance/service_chat/Application.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/data/DataBaseContainer.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/data/collection/MessageCollection.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/data/collection/TicketCollection.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/data/collection/mappers/MessageMapper.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/data/collection/mappers/TicketMapper.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/data/gateway/ChatGateway.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/di/ChatModule.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/domain/entity/Message.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/domain/entity/Ticket.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/domain/gateway/IChatGateway.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/domain/usecase/ManageChat.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/domain/usecase/ManageTicket.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/domain/utils/Exceptions.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/domain/utils/Extensions.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/endpoints/ChatRoutes.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/endpoints/models/Connection.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/endpoints/models/MessageDto.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/endpoints/models/SupportAgent.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/endpoints/models/TicketDto.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/endpoints/models/mappers/MessageMapper.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/endpoints/models/mappers/TicketMapper.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/endpoints/test.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/endpoints/utils/ErrorHandeler.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/plugins/DependencyInjection.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/plugins/Routing.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/plugins/StatusExceptions.kt
  service_chat/src/main/kotlin/org/thechance/service_chat/plugins/WebSockets.kt
Labels: Backbone Team

#514 backend/get-active-orders-for-user
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/ArabicLocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/EgyptLocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/EnglishLocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/IraqLocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/LocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/PalestineLocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/SyrainLocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/model/taxi/DeliveryTrackingResponse.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/model/taxi/RideTrackingResponse.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/model/taxi/TripDto.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/RestaurantService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/TaxiService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/utils/ErrorHandler.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/OrderRoute.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/TaxiRoute.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/UserRoute.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/utils/WebSocketServerHandler.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/endpoints/CartRoutes.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/endpoints/OrderRoutes.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/utils/SocketHandler.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/OrderCollection.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/mapper/OrderMapper.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/mapper/OrderWithRestaurantMapper.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/relationModels/OrderWithRestaurant.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/gateway/RestaurantGateway.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/gateway/RestaurantManagementGateway.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/entity/Order.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/gateway/IRestaurantManagementGateway.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/ManageOrderUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/ManageRestaurantDetailsUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/validation/OrderValidationUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/utils/exceptions/Exceptions.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/dto/trip/TripDto.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/dto/trip/TripMappers.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/dto/trip/WebSocketTrip.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/endpoints/TripRoutes.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/util/SocketHandler.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/data/collection/relationModel/TripWithTaxi.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/data/gateway/TaxiGateway.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/entity/Trip.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/gateway/ITaxiGateway.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/usecase/DriverTripsManagementUseCase.kt
  service_taxi/src/test/kotlin/org/thechance/service_taxi/domain/FakeGateway.kt
Labels: enhancement, Backbone Team

#520 fix error in sign up and add fun permission
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/PermissionRoute.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/UserRoute.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/usecases/IUserAccountManagementUseCase.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/endpoints/model/mapper/UserManagement.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/endpoints/userManagementRoutes.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/endpoints/userRoutes.kt
Labels: bug

#516 end-user/feature/cash-favorite-restaurants
  client_end_user/shared/src/commonMain/kotlin/data/gateway/local/LocalRestaurantGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/local/mapper/Restaurant.kt
  client_end_user/shared/src/commonMain/kotlin/data/local/model/RestaurantCollection.kt
  client_end_user/shared/src/commonMain/kotlin/di/GatewayModule.kt
  client_end_user/shared/src/commonMain/kotlin/di/LocalStorageModule.kt
  client_end_user/shared/src/commonMain/kotlin/domain/gateway/local/ILocalRestaurantGateway.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/ManageAuthunticationUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/ManageFavouriteUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/RestaurantDetailsMapper.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/RestaurantScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/ResturantUIState.kt
Labels: feature, Backbone Team

#498 Backend/refactor/cart
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/RestaurantService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/CartRoute.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/endpoints/CartRoutes.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/mappers/CartMapper.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/mapper/MealMapper.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/gateway/RestaurantManagementGateway.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/gateway/IRestaurantManagementGateway.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/MangeCartUseCase.kt
Labels: enhancement, Backbone Team

#530 fix add and remove favorite
  client_end_user/shared/src/commonMain/kotlin/data/gateway/local/LocalRestaurantGateway.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/ManageFavouriteUseCase.kt
Labels: Golden Team

#529 add restaurant and offer images
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/model/offer/OfferDto.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/RestaurantService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/OfferRoute.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/RestaurantRoute.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/endpoints/CategoryRoutes.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/CategoryDto.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/RestaurantDetailsDto.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/RestaurantDto.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/mappers/CategoryMapper.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/mappers/RestaurantMapper.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/CategoryCollection.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/RestaurantCollection.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/mapper/CategoryMapper.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/mapper/OrderWithRestaurantMapper.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/mapper/RestaurantMapper.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/relationModels/CategoryDetails.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/gateway/RestaurantOptionsGateway.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/entity/Category.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/entity/Order.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/entity/Restaurant.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/gateway/IRestaurantOptionsGateway.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/ManageCategoryUseCase.kt
Labels: Golden Team
