Repository TheChance101/beep-beep, pull requests merged in 2023-09, with the labels that each got.

#277 restaurant/enhancment/complete_restaurant_information_screen
  client_restaurant/shared/src/commonMain/kotlin/App.kt
  client_restaurant/shared/src/commonMain/kotlin/data/gateway/remote/BaseRemoteGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/data/gateway/remote/RestaurantRemoteGateWay.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/mapper/Location.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/mapper/Restaurant.kt
  client_restaurant/shared/src/commonMain/kotlin/di/LocalStorageModule.kt
  client_restaurant/shared/src/commonMain/kotlin/di/UseCaseModule.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/usecase/ManageRestaurantInfoUseCase.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/base/BaseScreenModel.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/base/ErrorState.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/base/ErrorType.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/information/RestaurantInformationScreen.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/information/RestaurantInformationScreenModel.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/information/RestaurantInformationUiEffect.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/login/LoginScreenModel.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/main/MainScreen.kt
Labels: enhancement

#294 Dashboard/fix/design
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/BpDropdownMenuItem.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/table/TotalItemsIndicator.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/resources/DrawableResources.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/resources/StringResources.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserScreenUiState.kt
  client_dashboard/common/src/commonMain/resources/ic_disable.svg
Labels: enhancement

#321 dashboard/fix/paging-arrows
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/table/ArrowIcon.kt
Labels: enhancement

#329 dashboard/feature/filters-reset-option
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/FilterBox.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/resources/StringResources.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantInteractionListener.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiInteractionListener.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserInteractionListener.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserScreenModel.kt
Labels: enhancement

#342 dashboard/feature/get-taxis-endpoint
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/fakegateway/TaxisFakeGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/FakeRemoteGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/TaxiGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/TaxisGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/mapper/TaxiMapper.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/model/PaginationResponse.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/model/TaxiDto.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/model/TaxiFiltrationDto.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/entity/CarColor.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/getway/IRemoteGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/getway/ITaxisGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/ManageTaxisUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiScreenModel.kt
  client_dashboard/desktop/src/jvmMain/kotlin/di/GatewayModule.kt
  client_dashboard/desktop/src/jvmMain/kotlin/di/NetworkModule.kt
Labels: enhancement

#343 dashboard/feature/handle-empty-list-state
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/table/BpTable.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/resources/StringResources.kt
Labels: enhancement

#347 dashboard/fix/seats-padding
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiScreen.kt
Labels: enhancement

#355 dashboard/feature/create-taxi-endpoint
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/fakegateway/TaxisFakeGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/TaxisGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/mapper/TaxiMapper.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/model/TaxiInfoDto.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/entity/NewTaxiInfo.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiUiState.kt
Labels: enhancement

#362 Dashboard/feature/implement validation
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/RestaurantGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/UsersGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/model/RestaurantCreateDto.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/IValidateRestaurantUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/RestaurantDialog.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginUIState.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantMapper.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantUiState.kt
  client_dashboard/desktop/src/jvmMain/kotlin/di/UseCaseModule.kt
Labels: enhancement

#361 dashboard/feature/implement-create-taxi-validation
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/TaxiValidationUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/CarColors.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/resources/StringResources.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiDialog.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiUiState.kt
  client_dashboard/desktop/src/jvmMain/kotlin/di/UseCaseModule.kt
Labels: enhancement

#380 End user/feature/register
  client_end_user/shared/src/commonMain/kotlin/data/gateway/remote/AuthorizationInterceptor.kt
  client_end_user/shared/src/commonMain/kotlin/data/gateway/remote/BaseGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/gateway/remote/UserRemoteRemoteGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/mapper/User.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/model/UserDto.kt
  client_end_user/shared/src/commonMain/kotlin/di/GatewayModule.kt
  client_end_user/shared/src/commonMain/kotlin/di/UseCaseModule.kt
  client_end_user/shared/src/commonMain/kotlin/di/screenModelsModule.kt
  client_end_user/shared/src/commonMain/kotlin/domain/gateway/IUserRemoteGateway.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/ManageAuthunticationUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/validation/IValidationUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/domain/utils/ErrorType.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/login/LoginScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/login/LoginScreenInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/login/LoginScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/login/LoginScreenUIEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/login/LoginScreenUIState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registration/RegistrationInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registration/RegistrationScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registration/RegistrationScreenEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registration/RegistrationScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registration/RegistrationUIState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registrationSubmit/RegistrationSubmitInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registrationSubmit/RegistrationSubmitScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registrationSubmit/RegistrationSubmitScreenEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registrationSubmit/RegistrationSubmitScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registrationSubmit/RegistrationSubmitUIState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/base/BaseScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/base/ErrorState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/BpBrandBackgroundContainer.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/HeadFirstCard.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/login/LoginScreenUIEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/main/MainContainer.kt
  client_end_user/shared/src/commonMain/kotlin/resources/DrawableResources.kt
  client_end_user/shared/src/commonMain/kotlin/resources/StringResources.kt
  client_end_user/shared/src/commonMain/resources/ic_back.xml
Labels: feature

#379 Dashboard/feature/implement validation
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/BaseGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/RestaurantGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/LoginUserUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/ManageLocationUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginUIState.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/resources/StringResources.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/util/ErrorState.kt
  client_dashboard/desktop/src/jvmMain/kotlin/di/GatewayModule.kt
  client_delivery/shared/shared.podspec
  client_restaurant/shared/shared.podspec
  client_taxi_driver/shared/shared.podspec
  design_system/shared/shared.podspec
Labels: enhancement

#386 add application id
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/IdentityService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/AuthenticationRoute.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/utils/Extentions.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/data/geteway/DataBaseGateway.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/gateway/IDataBaseGateway.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/usecases/IUserAccountManagementUseCase.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/usecases/IUserManagementUseCase.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/util/Role.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/endpoints/userRoutes.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/endpoints/util/Extensions.kt
Labels: feature

#399 End user/feature/navigation
  client_end_user/shared/src/commonMain/kotlin/presentation/PreferredFood/PreferredFoodScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/PreferredFood/PreferredFoodScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/app/App.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/app/AppScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/login/LoginScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registration/RegistrationScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/BpBrandBackgroundContainer.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/preferredMeal/PreferredMealScreen.kt
  design_system/shared/src/commonMain/kotlin/ui/composable/BpTextField.kt
Labels: feature

#401 Dashboard/feature/handle error state
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/CarColors.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginScreen.kt
Labels: enhancement

#404 taxi_service/refactor/add_taxi_type_validation
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/usecase/ManageTaxiUseCase.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/usecase/utils/Validations.kt
Labels: bug

#416 implement Update Taxi End point
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/TaxisGateway.kt
Labels: enhancement

#413 Hotfix/enduser/register statusbar
  client_end_user/shared/src/androidMain/kotlin/util/StatusBarColor.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registration/RegistrationScreen.kt
  client_end_user/shared/src/commonMain/kotlin/util/StatusBarColor.kt
  client_end_user/shared/src/iosMain/kotlin/util/StatusBarColor.kt
Labels: bug

#400 fix update/add restaurant
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/model/AddressDto.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/model/UserDto.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/model/restaurant/RestaurantDto.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/model/restaurant/RestaurantOptions.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/model/restaurant/RestaurantRequestDto.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/IdentityService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/RestaurantService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/RestaurantRoute.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/UserRoute.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/data/collection/WalletCollection.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/data/collection/mappers/DetailedUser.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/data/geteway/DataBaseGateway.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/entity/User.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/gateway/IDataBaseGateway.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/usecases/IUserAccountManagementUseCase.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/usecases/IUserAddressManagementUseCase.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/endpoints/model/UserDto.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/endpoints/model/mapper/User.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/endpoints/RestaurantRoutes.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/LocationDto.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/RestaurantDetailsDto.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/RestaurantDto.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/RestaurantOptionsDto.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/mappers/RestaurantMapper.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/mappers/RestaurantOptionsMapper.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/RestaurantCollection.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/mapper/RestaurantMapper.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/gateway/RestaurantGateway.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/entity/Restaurant.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/entity/RestaurantOptions.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/gateway/IRestaurantGateway.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/ControlRestaurantsUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/DiscoverRestaurantUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/ManageOrderUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/validation/RestaurantValidationUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/utils/Validation.kt
Labels: bug, feature

#422 end-user/feature/notification
  client_end_user/shared/src/commonMain/kotlin/data/gateway/remote/FakeRemoteGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/mapper/Date.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/mapper/Notification.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/mapper/Time.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/model/NotificationDto.kt
  client_end_user/shared/src/commonMain/kotlin/di/UseCaseModule.kt
  client_end_user/shared/src/commonMain/kotlin/di/screenModelsModule.kt
  client_end_user/shared/src/commonMain/kotlin/domain/entity/Date.kt
  client_end_user/shared/src/commonMain/kotlin/domain/entity/Notification.kt
  client_end_user/shared/src/commonMain/kotlin/domain/entity/Restaurant.kt
  client_end_user/shared/src/commonMain/kotlin/domain/entity/Time.kt
  client_end_user/shared/src/commonMain/kotlin/domain/gateway/IFakeRemoteGateway.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/ManageNotificationsUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/notification/NotificationInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/notification/NotificationScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/notification/NotificationScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/notification/NotificationUiEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/notification/NotificationUiState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/notification/combosable/NotificationCard.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/IStringResources.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/Arabic.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicEG.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicIQ.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicPS.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicSY.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/en/English.kt
Labels: Backbone Team

#415 dashboard/hotfix/taxi_fix_driver_username
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/fakegateway/TaxisFakeGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/FakeRemoteGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/RestaurantGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/TaxisGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/UsersGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/mapper/TaxiMapper.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/model/TaxiDto.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/model/TaxiInfoDto.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiScreenModel.kt
  client_dashboard/desktop/src/jvmMain/kotlin/di/NetworkModule.kt
Labels: bug

#425 end_user/fix/register_password_field
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registration/RegistrationScreen.kt
Labels: Backbone Team

#424 dashboard/fix/pagination
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/BaseGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/RestaurantGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/TaxisGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/UsersGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserScreenModel.kt
Labels: bug, Golden Team

#427 dashboard/feature/delete_taxi_by_id
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/fakegateway/TaxisFakeGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/TaxisGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/getway/ITaxisGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/ManageTaxisUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/resources/DrawableResources.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiInteractionListener.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiUiState.kt
Labels: Golden Team

#426 dashboard/fix/admin_username
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/local/gateway/LocalGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/local/gateway/UserLocalGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/local/model/ConfigurationCollection.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/fakegateway/FakeRemoteGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/fakegateway/RestaurantFakeGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/fakegateway/TaxisFakeGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/fakegateway/UsersFakeGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/FakeRemoteGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/TaxisGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/UsersGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/mapper/RestaurantMapper.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/mapper/TaxiMapper.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/model/RestaurantCreateDto.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/model/RestaurantDto.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/model/TaxiInfoDto.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/entity/NewTaxiInfo.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/entity/Restaurant.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/entity/Taxi.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/getway/ILocalGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/getway/IRemoteGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/getway/ITaxisGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/getway/IUserLocalGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/getway/IUsersGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/LoginUserUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/LogoutUserUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/ManageTaxisUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/ThemeManagementUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/UsersManagementUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginInteractionListener.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginUIState.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/main/MainContainer.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantMapper.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiUiState.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserScreenModel.kt
  client_dashboard/desktop/src/jvmMain/kotlin/di/GatewayModule.kt
  client_dashboard/desktop/src/jvmMain/kotlin/di/NetworkModule.kt
Labels: Golden Team

#429 end_user/refactor/remove_hard_coded_strings_from_screen_models
  client_end_user/shared/src/commonMain/kotlin/data/gateway/remote/AuthorizationInterceptor.kt
  client_end_user/shared/src/commonMain/kotlin/di/NetworkModule.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/login/LoginScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registration/RegistrationScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registrationSubmit/RegistrationSubmitScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/IStringResources.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/Arabic.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicEG.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicIQ.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicPS.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicSY.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/en/English.kt
Labels: bug, Backbone Team

#435 dashboard/feature/refactor_erorr_handling
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/BaseGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/mapper/RestaurantMapper.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/util/BpException.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/base/BaseScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/RestaurantDialog.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginUIState.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantUiState.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiDialog.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiUiState.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/util/ErrorState.kt
Labels: Golden Team

#437 end user orders history screen
  client_end_user/shared/src/commonMain/kotlin/data/gateway/fake/FakeOrderRemoteGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/gateway/fake/FakeRemoteGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/gateway/remote/RestaurantGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/mapper/Order.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/mapper/Trip.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/model/OrderDto.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/model/TripDto.kt
  client_end_user/shared/src/commonMain/kotlin/di/GatewayModule.kt
  client_end_user/shared/src/commonMain/kotlin/di/UseCaseModule.kt
  client_end_user/shared/src/commonMain/kotlin/di/screenModelsModule.kt
  client_end_user/shared/src/commonMain/kotlin/domain/entity/Order.kt
  client_end_user/shared/src/commonMain/kotlin/domain/entity/Trip.kt
  client_end_user/shared/src/commonMain/kotlin/domain/gateway/IOrderRemoteGateway.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/GetFavoriteRestaurantsUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/GetOrderHistoryUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/ManageNotificationsUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/ManageUserUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/main/Tab.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/orderHistory/OrderHistoryScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/orderHistory/OrderHistoryScreenInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/orderHistory/OrderHistoryScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/orderHistory/OrderHistoryScreenUiEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/orderHistory/OrderHistoryScreenUiState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/orderHistory/composable/HorizontalDivider.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/orderHistory/composable/MealOrderItem.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/orderHistory/composable/TripHistoryItem.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/orders/OrderScreen.kt
  client_end_user/shared/src/commonMain/kotlin/resources/DrawableResources.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/IStringResources.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/Arabic.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicEG.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicIQ.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicPS.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicSY.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/en/English.kt
  client_end_user/shared/src/commonMain/kotlin/util/Extensions.kt
  client_end_user/shared/src/commonMain/resources/icon_from_to.xml
Labels: feature, Backbone Team

#420 Resturant/feature/add charts
  client_restaurant/shared/build.gradle.kts
  client_restaurant/shared/src/commonMain/kotlin/data/gateway/FakeRemoteGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/data/gateway/remote/AuthorizationInterceptor.kt
  client_restaurant/shared/src/commonMain/kotlin/di/ScreenModelModule.kt
  client_restaurant/shared/src/commonMain/kotlin/di/UseCaseModule.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/gateway/IFakeRemoteGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/usecase/ManageOrderUseCase.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/main/MainScreen.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/main/MainScreenModel.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/main/MainScreenUIState.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/main/composables/ChartItem.kt
  client_restaurant/shared/src/commonMain/kotlin/util/Exetintions.kt
  gradle/libs.versions.toml
Labels: enhancement

#412 End user/refactor/apply language
  client_end_user/androidApp/src/androidMain/AndroidManifest.xml
  client_end_user/iosApp/iosApp/iOSApp.swift
  client_end_user/shared/src/androidMain/kotlin/util/StatusBarColor.kt
  client_end_user/shared/src/commonMain/kotlin/data/gateway/local/LocalConfigurationGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/gateway/remote/AuthorizationInterceptor.kt
  client_end_user/shared/src/commonMain/kotlin/di/AppModule.kt
  client_end_user/shared/src/commonMain/kotlin/di/ResourcesModule.kt
  client_end_user/shared/src/commonMain/kotlin/di/screenModelsModule.kt
  client_end_user/shared/src/commonMain/kotlin/domain/gateway/local/ILocalConfigurationGateway.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/ManageUserUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/MangeLanguageUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/app/App.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/app/AppScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/PreferredFoodCard.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/pickLanguage/PickLanguageScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/pickLanguage/PickLanguageUIState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/preferredFood/PreferredFoodInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/preferredFood/PreferredFoodScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/preferredFood/PreferredFoodScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/preferredFood/PreferredFoodUIEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/preferredFood/PreferredFoodUIState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/preferredMeal/PreferredScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/resources/BpResources.kt
  client_end_user/shared/src/commonMain/kotlin/util/LanguageCode.kt
  client_end_user/shared/src/commonMain/kotlin/util/LocalizationManager.kt
  client_end_user/shared/src/commonMain/kotlin/util/PrferedCuision.kt
  client_end_user/shared/src/commonMain/kotlin/util/languages.kt
Labels: enhancement, Backbone Team

#439 Get restaurants with search and filter
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/fakegateway/RestaurantFakeGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/RestaurantGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/mapper/RestaurantMapper.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/getway/IRestaurantGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/ManageRestaurantUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/EditablePriceBar.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantMapper.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantUiState.kt
Labels: Golden Team

#445 Restaurant/feature/update and add meal
  client_restaurant/shared/src/commonMain/kotlin/data/gateway/FakeRemoteGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/data/gateway/remote/BaseRemoteGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/data/gateway/remote/MealRemoteGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/mapper/Meal.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/model/MealDto.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/model/MealModificationDto.kt
  client_restaurant/shared/src/commonMain/kotlin/di/GatewayModule.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/entity/Meal.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/gateway/remote/IMealRemoteGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/usecase/ManageMealUseCase.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/usecase/ValidateManageMealUseCase.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/mealManagement/IMealBehavior.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/mealManagement/Mapper.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/mealManagement/MealDetails.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/mealManagement/MealScreen.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/mealManagement/MealScreenInteractionListener.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/mealManagement/MealScreenModelFactory.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/mealManagement/composable/MealContent.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/mealManagement/model/IMealCreationScreenModel.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/mealManagement/model/IMealEditorScreenModel.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/meals/MealsScreen.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/meals/MealsScreenModel.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/meals/MealsScreenUIEffect.kt
Labels: feature, Jewel Team

#418 Api gateway/feature/get token notification
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/ArabicLocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/EgyptLocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/EnglishLocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/IraqLocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/LocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/PalestineLocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/SyrainLocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/NotificationService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/utils/ErrorHandler.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/NotificationRoute.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/plugins/Routing.kt
  service_notification/src/main/kotlin/org/thechance/service_notification/data/mappers/User.kt
  service_notification/src/main/kotlin/org/thechance/service_notification/domain/usecases/IRegisterTokenUseCase.kt
  service_notification/src/main/kotlin/org/thechance/service_notification/endpoints/NotificationRoutes.kt
Labels: Backbone Team

#440 end_user/feature/all_cuisines
  client_end_user/shared/src/commonMain/kotlin/data/gateway/local/LocalConfigurationGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/gateway/remote/AuthorizationInterceptor.kt
  client_end_user/shared/src/commonMain/kotlin/data/gateway/remote/BaseGateway.kt
  client_end_user/shared/src/commonMain/kotlin/di/screenModelsModule.kt
  client_end_user/shared/src/commonMain/kotlin/domain/gateway/local/ILocalConfigurationGateway.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/ManageUserUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/MangeLanguageUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/app/App.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/login/LoginScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/login/LoginScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/login/LoginScreenUIState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registration/RegistrationScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registration/RegistrationScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registration/RegistrationUIState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registrationSubmit/RegistrationSubmitScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registrationSubmit/RegistrationSubmitScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registrationSubmit/RegistrationSubmitUIState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/BpImageLoader.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/PreferredFoodCard.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cuisines/CuisinesInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cuisines/CuisinesMappers.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cuisines/CuisinesScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cuisines/CuisinesScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cuisines/CuisinesUiEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cuisines/CuisinesUiState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeMappers.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreenInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreenUiEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreenUiState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/composable/CuisineCard.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/main/MainContainer.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/main/MainInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/main/MainScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/main/MainScreenUiEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/main/MainUiState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/main/Tab.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/preferredFood/PreferredFoodInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/preferredFood/PreferredFoodScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/preferredFood/PreferredFoodScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/preferredFood/PreferredFoodUIEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/preferredFood/PreferredFoodUIState.kt
  client_end_user/shared/src/commonMain/kotlin/resources/DrawableResources.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/IStringResources.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/Arabic.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicEG.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicIQ.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicPS.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicSY.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/en/English.kt
  client_end_user/shared/src/commonMain/kotlin/util/NavigatorExtensions.kt
  client_end_user/shared/src/commonMain/kotlin/util/PrferedCuision.kt
  client_end_user/shared/src/commonMain/resources/arrow_left.xml
Labels: feature, Backbone Team

#448 implement cart screen
  client_end_user/shared/src/commonMain/kotlin/data/gateway/fake/FakeRemoteGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/mapper/Cart.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/mapper/Meal.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/model/CartDto.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/model/CartMealDto.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/model/MealDto.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/model/NotificationDto.kt
  client_end_user/shared/src/commonMain/kotlin/di/UseCaseModule.kt
  client_end_user/shared/src/commonMain/kotlin/di/screenModelsModule.kt
  client_end_user/shared/src/commonMain/kotlin/domain/entity/Cart.kt
  client_end_user/shared/src/commonMain/kotlin/domain/entity/CartMeal.kt
  client_end_user/shared/src/commonMain/kotlin/domain/entity/Meal.kt
  client_end_user/shared/src/commonMain/kotlin/domain/gateway/IFakeRemoteGateway.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/ManageCartUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cart/CartInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cart/CartScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cart/CartScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cart/CartUiEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cart/CartUiState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cart/composable/ItemCart.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cart/composable/OrderInfoCard.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/exitinstion/Extinsions.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreenInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreenUiEffect.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/IStringResources.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/Arabic.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicEG.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicIQ.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicPS.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicSY.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/en/English.kt
Labels: feature, Backbone Team, Design

#449 dashboard/bug_fix/switching_theme
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/local/gateway/UserLocalGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/getway/IUserLocalGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/app/App.kt
  client_dashboard/desktop/src/jvmMain/kotlin/di/ScreenModelModule.kt
Labels: Golden Team

#452 Restaurant/feature/update restaurant
  client_restaurant/shared/src/commonMain/kotlin/data/gateway/remote/RestaurantRemoteGateWay.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/mapper/Restaurant.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/model/UpdateRestaurantDto.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/information/RestaurantInformationScreen.kt
Labels: feature, Jewel Team

#423 Dashboard/feature/no internet connection
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/BaseGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/util/BpException.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/BpNoInternetConnection.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/BpSnackBar.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/table/BpTable.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginInteractionListener.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginUIState.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/main/MainContainer.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/main/MainScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/main/MainUiState.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/overview/OverviewInteractionListener.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/overview/OverviewScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/overview/OverviewScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/overview/OverviewUiState.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/resources/DrawableResources.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantInteractionListener.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantUiState.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiInteractionListener.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiUiState.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserInteractionListener.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserScreenUiState.kt
  client_dashboard/common/src/commonMain/resources/ic_info_square.svg
  client_dashboard/common/src/commonMain/resources/no_internet_connection.png
Labels: enhancement, Golden Team

#453 support/feature/chat-screen
  client_support/common/src/commonMain/kotlin/org/thechance/common/data/fake_gateway/ChatFakeGateway.kt
  client_support/common/src/commonMain/kotlin/org/thechance/common/data/mapper/MessageMapper.kt
  client_support/common/src/commonMain/kotlin/org/thechance/common/data/mapper/TicketMapper.kt
  client_support/common/src/commonMain/kotlin/org/thechance/common/data/remote/model/MessageDto.kt
  client_support/common/src/commonMain/kotlin/org/thechance/common/data/remote/model/TicketDto.kt
  client_support/common/src/commonMain/kotlin/org/thechance/common/domain/entity/Message.kt
  client_support/common/src/commonMain/kotlin/org/thechance/common/domain/entity/NewMessage.kt
  client_support/common/src/commonMain/kotlin/org/thechance/common/domain/entity/Ticket.kt
  client_support/common/src/commonMain/kotlin/org/thechance/common/domain/gateway/IChatGateway.kt
  client_support/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/ManageMessagesUseCase.kt
  client_support/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/ManageTicketsUseCase.kt
  client_support/common/src/commonMain/kotlin/org/thechance/common/presentation/chat/ChatInteractionListener.kt
  client_support/common/src/commonMain/kotlin/org/thechance/common/presentation/chat/ChatScreen.kt
  client_support/common/src/commonMain/kotlin/org/thechance/common/presentation/chat/ChatScreenModel.kt
  client_support/common/src/commonMain/kotlin/org/thechance/common/presentation/chat/ChatUIEffect.kt
  client_support/common/src/commonMain/kotlin/org/thechance/common/presentation/chat/ChatUIState.kt
  client_support/common/src/commonMain/kotlin/org/thechance/common/presentation/composable/BpDropdownMenu.kt
  client_support/common/src/commonMain/kotlin/org/thechance/common/presentation/composable/MainAppbar.kt
  client_support/common/src/commonMain/kotlin/org/thechance/common/presentation/composable/modifier/CircleLayout.kt
  client_support/common/src/commonMain/kotlin/org/thechance/common/presentation/composable/modifier/CursorHoverIconHand.kt
  client_support/common/src/commonMain/kotlin/org/thechance/common/presentation/resources/DrawableResources.kt
  client_support/common/src/commonMain/kotlin/org/thechance/common/presentation/resources/StringResources.kt
  client_support/common/src/commonMain/resources/ic_drop_down_arrow_dark.svg
  client_support/common/src/commonMain/resources/ic_drop_down_arrow_light.svg
  client_support/common/src/commonMain/resources/ic_logout.svg
  client_support/common/src/commonMain/resources/ic_send.svg
  client_support/common/src/commonMain/resources/idle.png
  client_support/desktop/src/jvmMain/kotlin/di/GatewayModule.kt
  client_support/desktop/src/jvmMain/kotlin/di/ScreenModelModule.kt
  client_support/desktop/src/jvmMain/kotlin/di/UseCaseModule.kt
  design_system/shared/src/commonMain/kotlin/ui/composable/BpSimpleTextField.kt
Labels: enhancement, Golden Team

#385 End user/feature/profile
  client_end_user/shared/src/commonMain/kotlin/data/gateway/fake/FakeRemoteGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/gateway/local/LocalConfigurationGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/mapper/UserDetails.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/model/AddressDto.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/model/UserDetailsDto.kt
  client_end_user/shared/src/commonMain/kotlin/di/screenModelsModule.kt
  client_end_user/shared/src/commonMain/kotlin/domain/entity/Address.kt
  client_end_user/shared/src/commonMain/kotlin/domain/entity/UserDetails.kt
  client_end_user/shared/src/commonMain/kotlin/domain/gateway/IFakeRemoteGateway.kt
  client_end_user/shared/src/commonMain/kotlin/domain/gateway/local/ILocalConfigurationGateway.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/ManageAuthunticationUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/ManageUserUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/validation/IValidationUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registrationSubmit/RegistrationSubmitScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registrationSubmit/RegistrationSubmitUIState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/LoginMessage.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/TextOutLineButton.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/profile/ProfileInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/profile/ProfileScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/profile/ProfileScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/profile/ProfileUIEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/profile/ProfileUIState.kt
  client_end_user/shared/src/commonMain/kotlin/resources/DrawableResources.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/IStringResources.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/Arabic.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicEG.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicIQ.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicPS.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicSY.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/en/English.kt
  client_end_user/shared/src/commonMain/resources/logout_2.xml
  client_end_user/shared/src/commonMain/resources/need_login.png
Labels: Backbone Team

#451 backend/feature/remove_related_data_when_delete_user
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/RestaurantService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/TaxiService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/UserRoute.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/utils/Extentions.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/endpoints/RestaurantRoutes.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/gateway/RestaurantGateway.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/gateway/IRestaurantGateway.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/ControlRestaurantsUseCase.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/endpoints/TaxiRoutes.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/data/gateway/TaxiGateway.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/gateway/ITaxiGateway.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/usecase/ManageTaxiUseCase.kt
Labels: bug, Backbone Team

#455 dashboard/bug_fix/textfields_wrong_behavior_when_switching_theme
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserScreen.kt
  design_system/shared/src/commonMain/kotlin/ui/composable/BpSimpleTextField.kt
Labels: Golden Team

#461 dashboard/hotfix/dashboard_ui
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/BpSnackBar.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/scaffold/DashBoardScaffold.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/table/BpTable.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginUIState.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/main/MainContainer.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/main/MainScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/overview/OverviewScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserScreen.kt
  client_dashboard/common/src/commonMain/resources/ic_users_fill.svg
Labels: bug, enhancement, Golden Team

#462 create shimmer effect
  design_system/shared/src/commonMain/kotlin/ui/composable/modifier/shimmerEffect.kt
Labels: enhancement, Golden Team

#438 dashboard/feature/language_support
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/local/gateway/UserLocalGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/local/model/ConfigurationCollection.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/BaseGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/getway/IUserLocalGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/LoginUserUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/util/BpException.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/app/App.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/base/BaseScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/modifier/centeredOffset.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/scaffold/BpSideBarItem.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/scaffold/DashBoardScaffold.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/scaffold/DashboardSideBar.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/table/ArrowIcon.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginUIState.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/main/MainContainer.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/overview/OverviewUiState.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/resources/LocalizationManager.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/resources/Resources.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/resources/StringResources.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantUiState.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiUiState.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserScreenUiState.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/util/ErrorState.kt
  client_dashboard/desktop/src/jvmMain/kotlin/di/NetworkModule.kt
Labels: feature, Golden Team

#444 Delivery/feature/design new order
  client_delivery/shared/src/commonMain/kotlin/di/ScreenModelsModule.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/main/MainScreen.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/MapScreen.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/MapScreenInteractionsListener.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/MapScreenModel.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/MapScreenUiEffect.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/MapScreenUiState.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/OrderState.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/composable/AcceptedOrderCard.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/composable/DeliveredOrderCard.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/composable/DistanceInfo.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/composable/LoadingCard.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/composable/MapCard.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/composable/MapCardAnimation.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/composable/NewOrderCard.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/composable/OrderInfo.kt
  client_delivery/shared/src/commonMain/kotlin/resources/DrawableResources.kt
  client_delivery/shared/src/commonMain/kotlin/resources/StringResources.kt
  client_delivery/shared/src/commonMain/resources/close.xml
  client_delivery/shared/src/commonMain/resources/ic_clock_circle.xml
  client_delivery/shared/src/commonMain/resources/ic_location.xml
  client_delivery/shared/src/commonMain/resources/ic_map_point.xml
  client_delivery/shared/src/commonMain/resources/ic_point_on_map.xml
  client_delivery/shared/src/commonMain/resources/moon_stars.xml
  client_delivery/shared/src/commonMain/resources/ready_delivery_bike.png
  client_delivery/shared/src/commonMain/resources/sort.xml
  client_delivery/shared/src/commonMain/resources/sun.xml
  client_delivery/shared/src/commonMain/resources/test.jpg
Labels: feature, Ruby Team, Design

#464 refactor user screen ui state
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/fakegateway/UsersFakeGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/UsersGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/mapper/UserMapper.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/entity/Country.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/getway/IUsersGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/UsersManagementUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/PermissionsDialog.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/PermissionsFlowRow.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/overview/OverviewScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/overview/OverviewUiState.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/resources/StringResources.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserInteractionListener.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserScreenUiState.kt
Labels: enhancement, Golden Team

#458 Backend/refactor/search identity
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/model/UserOptions.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/IdentityService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/UserRoute.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/utils/Extentions.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/data/geteway/DataBaseGateway.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/entity/UserOptions.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/gateway/IDataBaseGateway.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/usecases/IUserManagementUseCase.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/endpoints/model/UserOptionsDto.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/endpoints/model/mapper/UserOptions.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/endpoints/userManagementRoutes.kt
Labels: enhancement, Backbone Team

#467 hotfix/get-favorite-restaurants
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/RestaurantService.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/endpoints/RestaurantRoutes.kt
Labels: bug, Backbone Team

#456 end_user/refactor/registration
  client_end_user/shared/src/commonMain/kotlin/data/gateway/remote/UserRemoteRemoteGateway.kt
  client_end_user/shared/src/commonMain/kotlin/domain/entity/UserCreation.kt
  client_end_user/shared/src/commonMain/kotlin/domain/gateway/IUserRemoteGateway.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/ManageAuthunticationUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/validation/IValidationUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/domain/utils/ErrorType.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registration/RegistrationInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registration/RegistrationScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registration/RegistrationScreenEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registration/RegistrationScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registration/RegistrationUIState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registrationSubmit/RegistrationSubmitInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registrationSubmit/RegistrationSubmitScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registrationSubmit/RegistrationSubmitScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registrationSubmit/RegistrationSubmitUIState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/base/ErrorState.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/IStringResources.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/Arabic.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicEG.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicIQ.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicPS.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicSY.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/en/English.kt
Labels: enhancement, Backbone Team

#446 search Meal
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/model/restaurant/ExploreRestaurantDto.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/RestaurantService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/MealRoute.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/RestaurantRoute.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/endpoints/RestaurantRoutes.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/ExploreRestaurantDto.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/RestaurantDetailsDto.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/mappers/RestaurantMapper.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/MealCollection.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/gateway/RestaurantGateway.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/gateway/RestaurantOptionsGateway.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/di/UseCasesModule.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/entity/Location.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/entity/RestaurantOptions.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/gateway/IRestaurantGateway.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/DiscoverRestaurantUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/ManageRestaurantDetailsUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/SearchUseCase.kt
Labels: bug, feature, Backbone Team

#468 Dashboard/feature/overview loading with shimmer effect
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/overview/OverviewScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/overview/OverviewUiState.kt
Labels: enhancement, Golden Team

#457 design-system/feature/create-three-dot-loading-indicator
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginUIState.kt
  client_support/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginScreen.kt
  client_support/common/src/commonMain/kotlin/org/thechance/common/presentation/login/LoginScreenModel.kt
  design_system/shared/src/commonMain/kotlin/ui/composable/BpButton.kt
  design_system/shared/src/commonMain/kotlin/ui/composable/BpThreeDotLoadingIndicator.kt
Labels: enhancement, Golden Team

#441 Api gatewat/feature/add get and update user info
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/model/UserDetailsDto.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/IdentityService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/UserRoute.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/data/collection/mappers/DetailedUser.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/data/collection/mappers/Wallet.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/data/geteway/DataBaseGateway.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/entity/Wallet.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/gateway/IDataBaseGateway.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/usecases/IUserAccountManagementUseCase.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/usecases/validation/IUserInfoValidationUseCase.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/endpoints/model/WalletDto.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/endpoints/model/mapper/Address.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/endpoints/model/mapper/Wallet.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/endpoints/userRoutes.kt
Labels: Backbone Team

#442 dashboard/feature/implement_taxi_search_with_filter
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/gateway/remote/TaxisGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/gateway/remote/mapper/TaxiMapper.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/gateway/remote/model/TaxiFiltrationDto.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/ManageTaxisUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiUiState.kt
Labels: enhancement, feature, Golden Team

#465 Add require login placeholder
  client_end_user/shared/src/commonMain/kotlin/data/gateway/local/LocalConfigurationGateway.kt
  client_end_user/shared/src/commonMain/kotlin/di/NetworkModule.kt
  client_end_user/shared/src/commonMain/kotlin/domain/gateway/local/ILocalConfigurationGateway.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/ManageAuthunticationUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/ManageCartUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/ManageUserUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/ContentVisibility.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/LoginRequiredPlaceholder.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cuisines/CuisinesScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreenUiState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/notification/NotificationInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/notification/NotificationScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/notification/NotificationScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/notification/NotificationUiEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/notification/NotificationUiState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/orderHistory/OrderHistoryScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/orderHistory/OrderHistoryScreenInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/orderHistory/OrderHistoryScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/orderHistory/OrderHistoryScreenUiEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/orderHistory/OrderHistoryScreenUiState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/profile/ProfileInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/profile/ProfileScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/profile/ProfileScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/profile/ProfileUIEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/profile/ProfileUIState.kt
  client_end_user/shared/src/commonMain/kotlin/resources/DrawableResources.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/IStringResources.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/Arabic.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicEG.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicIQ.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicPS.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicSY.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/en/English.kt
  client_end_user/shared/src/commonMain/kotlin/util/NavigatorExtensions.kt
  client_end_user/shared/src/commonMain/resources/login_placeholder_notification.png
  client_end_user/shared/src/commonMain/resources/login_placeholder_order_history.png
  client_end_user/shared/src/commonMain/resources/login_placeholder_profile.png
Labels: enhancement, Backbone Team

#475 dashboard/feature/add_shimmerEffect_to_bptable
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/table/BpTable.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiScreenModel.kt
Labels: enhancement, feature, Golden Team

#472 update retaurant
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/gateway/fake/RestaurantFakeGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/gateway/remote/RestaurantGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/gateway/remote/mapper/RestaurantMapper.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/gateway/remote/model/RestaurantCreateDto.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/gateway/remote/model/RestaurantDto.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/entity/Restaurant.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/entity/RestaurantInformation.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/getway/IRestaurantGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/ManageRestaurantUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/RestaurantDialog.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/TaxiDialog.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/resources/StringResources.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantInteractionListener.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantUiState.kt
Labels: feature, Golden Team

#466 End user/featur/meal details
  client_end_user/shared/src/commonMain/kotlin/data/gateway/fake/FakeRemoteGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/gateway/remote/BaseGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/gateway/remote/RestaurantGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/mapper/Restaurant.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/model/RestaurntDto.kt
  client_end_user/shared/src/commonMain/kotlin/di/UseCaseModule.kt
  client_end_user/shared/src/commonMain/kotlin/di/screenModelsModule.kt
  client_end_user/shared/src/commonMain/kotlin/domain/gateway/IFakeRemoteGateway.kt
  client_end_user/shared/src/commonMain/kotlin/domain/gateway/IRestaurantRemoteGateway.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/IManageFavouriteUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/mangeResturantDetailsUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/BottomSheet.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/BpImageCard.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/RatingBar.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/Composable/Chip.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/Composable/CloseButton.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/Composable/MealBottomSheet.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/Composable/NeedToLoginSheet.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/Composable/ToastMessage.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/RestaurantInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/RestaurantScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/RestaurantScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/RestaurantUIEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/resturantUIState.kt
  client_end_user/shared/src/commonMain/kotlin/resources/DrawableResources.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/IStringResources.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/Arabic.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicEG.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicIQ.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicPS.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicSY.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/en/English.kt
  client_end_user/shared/src/commonMain/resources/Heart.png
  client_end_user/shared/src/commonMain/resources/close.xml
  client_end_user/shared/src/commonMain/resources/heart_fill.xml
  client_end_user/shared/src/commonMain/resources/map_point.xml
  client_end_user/shared/src/commonMain/resources/minus_icon.xml
  client_end_user/shared/src/commonMain/resources/plus_icon.xml
  client_end_user/shared/src/commonMain/resources/scooter.xml
  client_end_user/shared/src/commonMain/resources/star.xml
  client_end_user/shared/src/commonMain/resources/star_half.xml
  client_end_user/shared/src/commonMain/resources/unread.xml
Labels: Backbone Team
