Repository TheChance101/beep-beep, pull requests merged in 2023-08, with the labels that each got.

#22 add trips curd
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/endpoints/TaxiRoutes.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/endpoints/TripRoutes.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/models/taxi/TaxiDto.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/models/taxi/TaxiMappers.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/models/trip/TripDto.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/models/trip/TripMappers.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/usecase/taxi/AddTaxiUseCase.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/usecase/taxi/DeleteTaxiUseCase.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/usecase/taxi/GetAllTaxesUseCase.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/usecase/taxi/GetTaxiByIdUseCase.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/usecase/taxi/TaxiUseCasesContainer.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/usecase/taxi/UpdateTaxiByIdUseCase.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/usecase/trip/AddTripUseCase.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/usecase/trip/DeleteTripUseCase.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/usecase/trip/GetAllTripsUseCase.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/usecase/trip/GetClientTripsHistoryUseCase.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/usecase/trip/GetDriverTripsHistoryUseCase.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/usecase/trip/GetTripByIdUseCase.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/usecase/trip/TripUseCasesContainer.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/usecase/trip/UpdateTripUseCase.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/data/DataBaseContainer.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/data/collection/TaxiCollection.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/data/collection/TripCollection.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/data/gateway/TaxiGatewayImpl.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/data/gateway/TripGatewayImpl.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/entity/Trip.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/gateway/TripGateway.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/usecase/taxi/AddTaxiUseCaseImpl.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/usecase/taxi/DeleteTaxiUseCaseImpl.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/usecase/taxi/GetAllTaxesUseCaseImpl.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/usecase/taxi/GetTaxiByIdUseCaseImpl.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/usecase/taxi/UpdateTaxiByIdUseCaseImpl.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/usecase/trip/AddTripUseCaseImpl.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/usecase/trip/DeleteTripUseCaseImpl.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/usecase/trip/GetAllTripsUseCaseImpl.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/usecase/trip/GetClientTripsHistoryUseCaseImpl.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/usecase/trip/GetDriverTripsHistoryUseCaseImpl.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/usecase/trip/GetTripByIdUseCaseImpl.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/usecase/trip/UpdateTripUseCaseImpl.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/plugins/Routing.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/utils/Constants.kt
Labels: documentation

#20 add address curd with restaurant relation
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/endpoints/AddressRoutes.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/endpoints/RestaurantRoutes.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/AddressDto.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/RestaurantDto.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/mappers/AddressMapper.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/mappers/RestaurantMapper.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/AddressCollection.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/RestaurantAddressesCollection.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/RestaurantCollection.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/mapper/AddressMapper.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/mapper/RestaurantMapper.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/gateway/AddressGateway.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/gateway/AddressGatewayImpl.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/gateway/CategoryGatewayImp.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/gateway/RestaurantGateway.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/gateway/RestaurantGatewayImp.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/entity/Address.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/entity/Restaurant.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/plugins/Routing.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/usecase/address/AddAddressToRestaurantUseCaseImpl.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/usecase/address/AddressUseCases.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/usecase/address/AddressUseCasesContainer.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/usecase/address/CreateAddressUseCaseImpl.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/usecase/address/DeleteAddressUseCaseImpl.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/usecase/address/DeleteAddressesInRestaurantUseCaseImpl.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/usecase/address/GetAddressDetailsUseCaseImpl.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/usecase/address/GetAddressesInRestaurantUseCaseImpl.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/usecase/address/GetAddressesUseCaseImpl.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/usecase/address/UpdateAddressUseCaseImpl.kt
Labels: documentation

#74 restaurant/feature/add_testing_category
  service_restaurant/build.gradle.kts
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/utils/Exceptions.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/utils/Validation.kt
  service_restaurant/src/test/kotlin/org/thechance/service_restaurant/utils/CategoryValidationsTest.kt
  service_restaurant/src/test/kotlin/org/thechance/service_restaurant/utils/CheckIdsValidationTest.kt
  service_restaurant/src/test/kotlin/org/thechance/service_restaurant/utils/ValidateUpdateMealTest.kt
  service_restaurant/src/test/kotlin/org/thechance/service_restaurant/utils/ValidationKtTest.kt
Labels: unit test

#70 Restaurant/test/add test general functions
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/endpoints/CategoryRoutes.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/endpoints/CuisineRoutes.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/endpoints/RestaurantRoutes.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/mappers/RestaurantMapper.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/utils/ErrorHandeler.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/utils/Extensions.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/ControlRestaurantsUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/DiscoverRestaurantUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/ManageCategoryUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/ManageCuisineUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/ManageMealUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/ManageRestaurantDetailsUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/utils/Exceptions.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/utils/Validation.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/utils/ValidationHandler.kt
  service_restaurant/src/test/kotlin/org/thechance/service_restaurant/domain/utils/ValidationHandlerKtTest.kt
  service_restaurant/src/test/kotlin/org/thechance/service_restaurant/utils/CategoryValidationsTest.kt
  service_restaurant/src/test/kotlin/org/thechance/service_restaurant/utils/CheckIdsValidationTest.kt
  service_restaurant/src/test/kotlin/org/thechance/service_restaurant/utils/ValidateUpdateMealTest.kt
  service_restaurant/src/test/kotlin/org/thechance/service_restaurant/utils/ValidationKtTest.kt
Labels: unit test

#63 restaurant/feature/add_testing
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/RestaurantDetailsDto.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/mappers/RestaurantMapper.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/RestaurantCollection.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/utils/Extensions.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/entity/Restaurant.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/ControlRestaurantsUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/DiscoverRestaurantUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/ManageCategoryUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/ManageCuisineUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/ManageMealUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/ManageRestaurantDetailsUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/validation/MealValidation.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/validation/RestaurantValidation.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/validation/Validation.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/utils/Validation.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/utils/ValidationHandler.kt
  service_restaurant/src/test/kotlin/org/thechance/service_restaurant/domain/validation/CategoryValidationsTest.kt
  service_restaurant/src/test/kotlin/org/thechance/service_restaurant/domain/validation/MealValidationTest.kt
  service_restaurant/src/test/kotlin/org/thechance/service_restaurant/domain/validation/RestaurantValidationTest.kt
  service_restaurant/src/test/kotlin/org/thechance/service_restaurant/domain/validation/ValidationTest.kt
  service_restaurant/src/test/kotlin/org/thechance/service_restaurant/utils/CheckIdsValidationTest.kt
  service_restaurant/src/test/kotlin/org/thechance/service_restaurant/utils/ValidateUpdateMealTest.kt
  service_restaurant/src/test/kotlin/org/thechance/service_restaurant/utils/ValidationKtTest.kt
Labels: unit test

#77 restaurant/refactor/di
  service_restaurant/build.gradle.kts
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/DataBaseContainer.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/gateway/RestaurantGateway.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/gateway/RestaurantOptionsGateway.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/di/AppModule.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/di/DataBaseModule.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/di/GatewaysModule.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/di/UseCasesModule.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/gateway/IRestaurantOptionsGateway.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/ControlRestaurantsUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/DiscoverRestaurantUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/ManageCategoryUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/ManageCuisineUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/ManageMealUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/ManageRestaurantDetailsUseCase.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/validation/MealValidation.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/validation/RestaurantValidation.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/validation/Validation.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/plugins/DependencyInjection.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/plugins/Serialization.kt
Labels: enhancement

#75 notification/feature/send-notifications-by-topic
  service_notification/src/main/kotlin/org/thechance/service_notification/Application.kt
  service_notification/src/main/kotlin/org/thechance/service_notification/data/DatabaseContainer.kt
  service_notification/src/main/kotlin/org/thechance/service_notification/data/collection/GroupUser.kt
  service_notification/src/main/kotlin/org/thechance/service_notification/data/gateway/DatabaseGateway.kt
  service_notification/src/main/kotlin/org/thechance/service_notification/data/gateway/PushNotificationGateway.kt
  service_notification/src/main/kotlin/org/thechance/service_notification/di/NotificationModule.kt
  service_notification/src/main/kotlin/org/thechance/service_notification/domain/gateway/IDatabaseGateway.kt
  service_notification/src/main/kotlin/org/thechance/service_notification/domain/gateway/IPushNotificationGateway.kt
  service_notification/src/main/kotlin/org/thechance/service_notification/domain/model/Topic.kt
  service_notification/src/main/kotlin/org/thechance/service_notification/domain/usecases/GetNotificationHistoryUseCase.kt
  service_notification/src/main/kotlin/org/thechance/service_notification/domain/usecases/NotificationManagementUseCase.kt
  service_notification/src/main/kotlin/org/thechance/service_notification/domain/usecases/RegisterTokenUseCase.kt
  service_notification/src/main/kotlin/org/thechance/service_notification/domain/usecases/SendNotificationContainerUseCase.kt
  service_notification/src/main/kotlin/org/thechance/service_notification/endpoints/NotificationHistoryRoutes.kt
  service_notification/src/main/kotlin/org/thechance/service_notification/endpoints/NotificationManagementRoutes.kt
  service_notification/src/main/kotlin/org/thechance/service_notification/endpoints/NotificationRoutes.kt
  service_notification/src/main/kotlin/org/thechance/service_notification/plugins/Routing.kt
Labels: enhancement

#79 taxi/refactor/di
  service_taxi/src/main/kotlin/org/thechance/service_taxi/di/AppModule.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/di/DataBaseModule.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/di/GatewayModule.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/di/UseCasesModule.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/plugins/DependencyInjection.kt
Labels: enhancement

#83 handle the name of the classes to be like the standred of the project
  service_identity/src/main/kotlin/org/thechance/service_identity/data/geteway/DataBaseGateway.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/gateway/IDataBaseGateway.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/usecases/IManageUserAccountUseCase.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/usecases/IManageUserAddressUseCase.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/usecases/IPermissionManagementUseCase.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/usecases/IUserManagementUseCase.kt
Labels: enhancement

#119 api-getway/feature/add_refresh_token
  api_gateway/src/main/kotlin/org/thechance/api_gateway/Application.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/gateway/ApiGateway.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/security/ITokenServiceImpl.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/domain/entity/TokenConfiguration.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/domain/gateway/IApiGateway.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/domain/security/ITokenService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/domain/usecase/UserAccountManagementUseCase.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/UserRoute.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/data/collection/RefreshTokenCollection.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/data/geteway/DataBaseGateway.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/gateway/IDataBaseGateway.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/usecases/IUserAccountManagementUseCase.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/endpoints/model/UserTokenDto.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/endpoints/userRoutes.kt
Labels: enhancement

#123 api-getway/localization_support
  api_gateway/build.gradle.kts
  api_gateway/src/main/kotlin/org/thechance/api_gateway/Application.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/gateway/ApiGateway.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/gateway/ResourcesGateway.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/mappers/UserTokensMapper.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/domain/entity/ApiGatewayExceptions.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/domain/gateway/IResourcesGateway.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/domain/usecase/GetLocalizedErrorMessagesUseCase.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/domain/usecase/UserAccountManagementUseCase.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/domain/usecase/util/TryToExecute.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/UserRoute.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/model/TokensDto.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/utils/ExtractLocalizationHeader.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/plugins/ConfigureStatusPages.kt
  api_gateway/src/main/resources/errors_ar.properties
  api_gateway/src/main/resources/errors_ar_EG.properties
  api_gateway/src/main/resources/errors_ar_IQ.properties
  api_gateway/src/main/resources/errors_ar_PS.properties
  api_gateway/src/main/resources/errors_en.properties
  service_identity/src/main/kotlin/org/thechance/service_identity/data/geteway/DataBaseGateway.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/entity/exceptions.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/usecases/IUserAccountManagementUseCase.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/util/error_codes.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/plugins/StatusPages.kt
Labels: enhancement

#130 api-getway/return_error_codes_with_error_messages
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/gateway/IResourcesGateway.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/gateway/ResourcesGateway.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/model/ApiGatewayExceptions.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/utils/ServerResponse.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/utils/extentions.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/plugins/ConfigureStatusPages.kt
Labels: enhancement

#145 api-getway/fix/refactor_tokens_generation
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/gateway/ApiGateway.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/gateway/ITokenService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/gateway/ResourcesGateway.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/security/ITokenServiceImpl.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/IApiGateway.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/UserRoute.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/plugins/ConfigureSecurity.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/data/geteway/DataBaseGateway.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/gateway/IDataBaseGateway.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/domain/usecases/IUserAccountManagementUseCase.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/endpoints/userRoutes.kt
Labels: bug

#144 Feature/dashboard/permissions dialog
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/App.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/FakeRemoteGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/PermissionsDialog.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/uistate/UserScreenUiState.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/composables/UserRow.kt
Labels: enhancement

#202 Fix/resturant/handle mappers
  client_restaurant/shared/src/commonMain/kotlin/data/gateway/FakeRemoteGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/data/gateway/LocalConfigurationGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/data/gateway/RemoteCategoryGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/data/gateway/RemoteCuisineGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/data/gateway/RemoteIdentityGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/data/gateway/RemoteMealGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/data/gateway/RemoteOrderGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/data/gateway/RemoteRestaurantGateWay.kt
  client_restaurant/shared/src/commonMain/kotlin/data/local/gateway/LocalGateWay.kt
  client_restaurant/shared/src/commonMain/kotlin/data/local/mapper/Token.kt
  client_restaurant/shared/src/commonMain/kotlin/data/local/model/FlagDto.kt
  client_restaurant/shared/src/commonMain/kotlin/data/local/model/TokenDto.kt
  client_restaurant/shared/src/commonMain/kotlin/data/local/model/UserConfigurationCollection.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/gateway/RemoteGateWay.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/mapper/Address.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/mapper/Category.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/mapper/Cuisine.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/mapper/Meal.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/mapper/Order.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/mapper/OrderedMeal.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/mapper/Restaurant.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/model/AddressDto.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/model/CategoryDto.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/model/CuisineDto.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/model/MealDto.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/model/OrderDto.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/model/OrderMealDto.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/model/RestaurantDto.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/model/UserTokensDto.kt
  client_restaurant/shared/src/commonMain/kotlin/di/GatewayModule.kt
  client_restaurant/shared/src/commonMain/kotlin/di/LocalStorageModule.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/gateway/IFakeRemoteGateWay.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/gateway/ILocalConfigurationGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/gateway/IRemoteCategoryGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/gateway/IRemoteCuisineGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/gateway/IRemoteIdentityGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/gateway/IRemoteMealGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/gateway/IRemoteOrderGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/gateway/IRemoteRestaurantGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/usecase/GetOwnerRestaurantsUseCase.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/usecase/LoginUserUseCase.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/usecase/ManageMealUseCase.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/usecase/ManageOrderUseCase.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/usecase/ManageRestaurantInfoUseCase.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/usecase/MangeCuisineUseCase.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/base/BaseScreenModel.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/base/ErrorState.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/base/ErrorType.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/login/LoginScreen.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/login/LoginScreenModel.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/login/LoginScreenUIState.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/main/MainScreenModel.kt
Labels: enhancement

#227 feature/dashboard/remove-admin-entity
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/FakeRemoteGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/gateway/RemoteGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/model/AdminDto.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/entity/Admin.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/getway/IRemoteGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/GetUserInfoUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/main/AdminUiState.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/main/MainScreenModel.kt
Labels: enhancement
