Repository TheChance101/beep-beep, pull requests merged in 2023-11, with the labels that each got.

#531 dashboard/feature/add_image_to_cuisine
  client_dashboard/common/build.gradle.kts
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/gateway/fake/RestaurantFakeGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/gateway/remote/RestaurantGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/gateway/remote/mapper/CuisineMapper.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/gateway/remote/model/CuisineDto.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/entity/Cuisine.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/getway/IRestaurantGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/MangeCuisinesUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/resources/DrawableResources.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantInteractionListener.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantUiState.kt
  client_dashboard/common/src/commonMain/resources/add_image.svg
  client_dashboard/desktop/src/jvmMain/kotlin/di/NetworkModule.kt
Labels: feature, Backbone Team

#533 dashboard/feature/add_offer
  client_dashboard/common/build.gradle.kts
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/gateway/fake/RestaurantFakeGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/gateway/remote/RestaurantGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/gateway/remote/mapper/OfferMapper.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/gateway/remote/model/OfferDto.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/entity/Offer.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/getway/IRestaurantGateway.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/ExploreDashboardUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/IValidateRestaurantUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/ManageLocationUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/ManageRestaurantUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/ManageRevenueShareUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/ManageTaxisUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/ManageThemeUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/ManageUsersUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/MangeCuisinesUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/MangeOffersUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/TaxiValidationUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/domain/usecase/UsersManagementUseCase.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/app/AppScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/composables/RestaurantDialog.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/main/MainScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/overview/OverviewScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/resources/DrawableResources.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/resources/Resources.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/resources/StringResources.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantInteractionListener.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantScreen.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantUiState.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/taxi/TaxiScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserScreenModel.kt
  client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/util/Extensions.kt
  client_dashboard/common/src/commonMain/resources/add_image.svg
  client_dashboard/common/src/commonMain/resources/edit_image.svg
  client_dashboard/desktop/src/jvmMain/kotlin/di/UseCaseModule.kt
Labels: feature, Backbone Team

#546 restaurant/fix/add_image_restaurant
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/RestaurantRoute.kt
Labels: bug

#548 End user/push notifications ios
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/ArabicLocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/EgyptLocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/EnglishLocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/IraqLocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/LocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/PalestineLocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/localizedMessages/languages/SyrainLocalizedMessages.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/model/restaurant/OrderStatus.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/model/taxi/TripStatus.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/NotificationService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/AuthenticationRoute.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/OrderRoute.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/TaxiRoute.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/utils/WebSocketServerHandler.kt
  client_end_user/androidApp/google-services.json
  client_end_user/iosApp/Podfile.lock
  client_end_user/iosApp/Pods/Local Podspecs/shared.podspec.json
  client_end_user/iosApp/Pods/Manifest.lock
  client_end_user/iosApp/Pods/Pods.xcodeproj/project.pbxproj
  client_end_user/iosApp/Pods/Target Support Files/Pods-iosApp/Pods-iosApp-acknowledgements.markdown
  client_end_user/iosApp/Pods/Target Support Files/Pods-iosApp/Pods-iosApp-acknowledgements.plist
  client_end_user/iosApp/Pods/Target Support Files/Pods-iosApp/Pods-iosApp-resources-Debug-input-files.xcfilelist
  client_end_user/iosApp/Pods/Target Support Files/Pods-iosApp/Pods-iosApp-resources-Debug-output-files.xcfilelist
  client_end_user/iosApp/Pods/Target Support Files/Pods-iosApp/Pods-iosApp-resources-Release-input-files.xcfilelist
  client_end_user/iosApp/Pods/Target Support Files/Pods-iosApp/Pods-iosApp-resources-Release-output-files.xcfilelist
  client_end_user/iosApp/Pods/Target Support Files/Pods-iosApp/Pods-iosApp-resources.sh
  client_end_user/iosApp/Pods/Target Support Files/Pods-iosApp/Pods-iosApp.debug.xcconfig
  client_end_user/iosApp/Pods/Target Support Files/Pods-iosApp/Pods-iosApp.release.xcconfig
  client_end_user/iosApp/Pods/Target Support Files/shared/shared.debug.xcconfig
  client_end_user/iosApp/Pods/Target Support Files/shared/shared.release.xcconfig
  client_end_user/iosApp/iosApp.xcodeproj/project.pbxproj
  client_end_user/iosApp/iosApp/Info.plist
  client_end_user/iosApp/iosApp/Preview Content/Preview Assets.xcassets/1670322289884_test.imageset/Contents.json
  client_end_user/iosApp/iosApp/iOSApp.swift
  client_end_user/shared/build.gradle.kts
  client_end_user/shared/shared.podspec
  client_end_user/shared/src/commonMain/kotlin/data/gateway/remote/UserGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/gateway/service/IFireBaseMessageService.kt
  client_end_user/shared/src/commonMain/kotlin/di/GatewayModule.kt
  client_end_user/shared/src/commonMain/kotlin/di/NetworkModule.kt
  client_end_user/shared/src/iosMain/kotlin/FireBaseMessageService.kt
  client_end_user/shared/src/iosMain/kotlin/Helper.kt
  service_notification/src/main/kotlin/org/thechance/service_notification/data/DatabaseContainer.kt
  service_notification/src/main/kotlin/org/thechance/service_notification/data/gateway/DatabaseGateway.kt
Labels: feature

#555 fix/login-response-has-user-id
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/model/UserTokensResponse.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/IdentityService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/AuthenticationRoute.kt
Labels: bug

#506 Delivery/feature/order implementation
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/TaxiService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/CartRoute.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/OrderRoute.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/TaxiRoute.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/utils/WebSocketServerHandler.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/plugins/WebSockets.kt
  client_delivery/.gitignore
  client_delivery/androidApp/src/androidMain/assets/bing_map/map/logo-respircov.png
  client_delivery/androidApp/src/androidMain/assets/bing_map/map/user_pin.svg
  client_delivery/shared/src/commonMain/kotlin/data/gateway/local/LocalConfigurationGateway.kt
  client_delivery/shared/src/commonMain/kotlin/data/gateway/remote/BaseRemoteGateway.kt
  client_delivery/shared/src/commonMain/kotlin/data/gateway/remote/IdentityRemoteGateway.kt
  client_delivery/shared/src/commonMain/kotlin/data/gateway/remote/MapRemoteGateway.kt
  client_delivery/shared/src/commonMain/kotlin/data/local/model/UserConfigurationCollection.kt
  client_delivery/shared/src/commonMain/kotlin/data/remote/mapper/Location.kt
  client_delivery/shared/src/commonMain/kotlin/data/remote/mapper/Order.kt
  client_delivery/shared/src/commonMain/kotlin/data/remote/mapper/Taxi.kt
  client_delivery/shared/src/commonMain/kotlin/data/remote/model/LocationDto.kt
  client_delivery/shared/src/commonMain/kotlin/data/remote/model/OrderDto.kt
  client_delivery/shared/src/commonMain/kotlin/data/remote/model/TaxiDto.kt
  client_delivery/shared/src/commonMain/kotlin/di/GatewayModule.kt
  client_delivery/shared/src/commonMain/kotlin/di/NetworkModule.kt
  client_delivery/shared/src/commonMain/kotlin/di/ScreenModelsModule.kt
  client_delivery/shared/src/commonMain/kotlin/di/UseCaseModule.kt
  client_delivery/shared/src/commonMain/kotlin/domain/entity/Order.kt
  client_delivery/shared/src/commonMain/kotlin/domain/entity/Taxi.kt
  client_delivery/shared/src/commonMain/kotlin/domain/gateway/local/ILocalConfigurationGateway.kt
  client_delivery/shared/src/commonMain/kotlin/domain/gateway/remote/IIdentityRemoteGateway.kt
  client_delivery/shared/src/commonMain/kotlin/domain/gateway/remote/IMapRemoteGateway.kt
  client_delivery/shared/src/commonMain/kotlin/domain/usecase/ManageLoginUserUseCase.kt
  client_delivery/shared/src/commonMain/kotlin/domain/usecase/ManageOrderUseCase.kt
  client_delivery/shared/src/commonMain/kotlin/domain/utils/ErrorType.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/base/BaseScreenModel.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/MapScreen.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/MapScreenModel.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/MapScreenUiState.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/MapUiMapper.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/composable/AcceptedOrderCard.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/composable/DeliveredOrderCard.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/composable/MapView.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/composable/NewOrderCard.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/composable/OrderInfo.kt
  service_location/src/main/kotlin/org/thechance/service_location/plugins/WebSockets.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/plugins/WebSockets.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/api/endpoints/TaxiRoutes.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/data/gateway/TaxiGateway.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/gateway/ITaxiGateway.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/domain/usecase/ManageTaxiUseCase.kt
  service_taxi/src/main/kotlin/org/thechance/service_taxi/plugins/WebSocket.kt
Labels: enhancement, feature

#565 fix/order-status-is-not-resturned-with-collect-orders-websocket
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/model/restaurant/OrderDto.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/OrderRoute.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/utils/WebSocketServerHandler.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/mapper/FoodOrder.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/model/FoodOrderDto.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/OrderDto.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/mappers/OrderMapper.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/collection/mapper/OrderMapper.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/entity/Order.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/entity/mapper/OrderMapper.kt
Labels: bug

#568 Fix/restaurant charts
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/RestaurantService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/RestaurantRoute.kt
  client_end_user/androidApp/google-services.json
  client_restaurant/shared/src/commonMain/kotlin/data/gateway/local/LocalConfigurationGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/data/gateway/remote/MealRemoteGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/data/gateway/remote/OrderRemoteGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/data/local/model/UserConfigurationCollection.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/model/PaginationResponse.kt
  client_restaurant/shared/src/commonMain/kotlin/di/NetworkModule.kt
  client_restaurant/shared/src/commonMain/kotlin/di/ScreenModelModule.kt
  client_restaurant/shared/src/commonMain/kotlin/di/UseCaseModule.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/gateway/local/ILocalConfigurationGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/usecase/GetRestaurantsUseCase.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/usecase/LoginUserUseCase.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/usecase/ManageOrderUseCase.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/usecase/ManageRestaurantInfoUseCase.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/app/App.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/app/AppScreenModel.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/app/AppUiState.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/composable/RestaurantInformation.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/login/LoginScreen.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/login/LoginScreenModel.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/login/LoginScreenUIEffect.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/main/MainScreen.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/main/MainScreenModel.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/main/MainScreenUIState.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/main/composables/ChartItem.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/main/composables/ChartLoadingEffect.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/restaurantSelection/RestaurantSelectionScreen.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/restaurantSelection/RestaurantSelectionScreenModel.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/restaurantSelection/RestaurantSelectionScreenUIEffect.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/restaurantSelection/RestaurantUIState.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/endpoints/RestaurantRoutes.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/gateway/RestaurantGateway.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/gateway/IRestaurantGateway.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/DiscoverRestaurantUseCase.kt
Labels: bug, enhancement

#570 profile error endpoint
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/model/offer/OfferRestaurantsDto.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/AuthenticationRoute.kt
  client_end_user/.gitignore
  client_end_user/androidApp/google-services.json
  client_end_user/shared/src/commonMain/kotlin/data/gateway/fake/FakeRestaurantGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/gateway/remote/RestaurantGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/gateway/remote/UserGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/gateway/remote/pagesource/RestaurantsPagingSource.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/mapper/Offer.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/mapper/Restaurant.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/model/AddressDto.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/model/OfferDto.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/model/RestaurntDto.kt
  client_end_user/shared/src/commonMain/kotlin/di/GatewayModule.kt
  client_end_user/shared/src/commonMain/kotlin/di/screenModelsModule.kt
  client_end_user/shared/src/commonMain/kotlin/domain/gateway/IRestaurantGateway.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/ExploreRestaurantUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/restaurants/RestaurantsListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/restaurants/RestaurantsScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/restaurants/RestaurantsScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/restaurants/RestaurantsUIEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/restaurants/ResturantsUIState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/RestaurantScreen.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/IStringResources.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/Arabic.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicEG.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicIQ.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicPS.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicSY.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/en/English.kt
  service_identity/src/main/kotlin/org/thechance/service_identity/endpoints/model/UserDto.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/CategoryDetailsDto.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/models/mappers/CategoryMapper.kt
Labels: bug

#571 fix update images
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/ImageService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/MealRoute.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/RestaurantRoute.kt
Labels: Golden Team

#588 delivery/feature/emit-location
  client_delivery/shared/src/commonMain/kotlin/data/gateway/remote/MapRemoteGateway.kt
  client_delivery/shared/src/commonMain/kotlin/data/remote/mapper/Location.kt
  client_delivery/shared/src/commonMain/kotlin/domain/gateway/remote/IMapRemoteGateway.kt
  client_delivery/shared/src/commonMain/kotlin/domain/usecase/ManageOrderUseCase.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/MapScreenModel.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/MapScreenUiState.kt
Labels: enhancement, feature

#550 restaurant/feature/order_sockt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/UserRoute.kt
  client_restaurant/shared/src/commonMain/kotlin/data/gateway/local/LocalConfigurationGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/data/gateway/remote/OrderRemoteGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/data/local/model/UserConfigurationCollection.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/mapper/Location.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/mapper/Trip.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/model/AddressInfoDto.kt
  client_restaurant/shared/src/commonMain/kotlin/data/remote/model/TripDto.kt
  client_restaurant/shared/src/commonMain/kotlin/di/ScreenModelModule.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/entity/Location.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/entity/Trip.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/gateway/local/ILocalConfigurationGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/gateway/remote/IOrderRemoteGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/usecase/LoginUserUseCase.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/usecase/ManageOrderUseCase.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/usecase/ManageRestaurantInfoUseCase.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/base/BaseScreenModel.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/main/MainScreen.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/main/MainScreenInteractionListener.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/main/MainScreenModel.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/order/OrderScreen.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/order/OrderScreenInteractionListener.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/order/OrderScreenModel.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/order/OrderScreenUiEffect.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/order/OrderScreenUiState.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/orderHistory/Mappers.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/orderHistory/OrdersHistoryScreen.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/restaurantSelection/RestaurantSelectionScreen.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/restaurantSelection/RestaurantSelectionScreenInteractionListener.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/restaurantSelection/RestaurantSelectionScreenModel.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/restaurantSelection/RestaurantUIState.kt
Labels: bug, feature, Backbone Team

#598 feature/restaurant/image-loader
  client_delivery/shared/build.gradle.kts
  client_delivery/shared/src/androidMain/kotlin/util/GenerateImageLoader.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/composable/OrderInfo.kt
  client_delivery/shared/src/commonMain/kotlin/resources/BpResources.kt
  client_delivery/shared/src/commonMain/kotlin/resources/DrawableResources.kt
  client_delivery/shared/src/commonMain/kotlin/util/GenerateImageLoader.kt
  client_delivery/shared/src/commonMain/resources/restaurant_error.png
  client_delivery/shared/src/commonMain/resources/restaurant_error_dark.jpg
  client_delivery/shared/src/iosMain/kotlin/util/GenerateImageLoader.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/mapper/Cart.kt
  client_end_user/shared/src/commonMain/kotlin/data/remote/mapper/MealCart.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cart/composable/ItemCart.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/BpImageCard.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/BpImageLoader.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/ImageSlider.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/MealBottomSheet.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/MealCard.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/PreferredFoodCard.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/composable/CuisineCard.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/orderHistory/composable/MealOrderItem.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/restaurants/RestaurantsScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/RestaurantScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/search/SearchScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/taxi/TaxiOrderScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/taxi/destinationSearch/SearchDestinationScreen.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/composable/BpEmptyScreen.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/composable/MealCard.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/meals/MealsScreen.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/meals/MealsScreenUIState.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/order/OrderScreen.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/order/composable/OrderCard.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/orderHistory/OrdersHistoryScreen.kt
  client_restaurant/shared/src/commonMain/kotlin/resources/DrawableResources.kt
  client_restaurant/shared/src/commonMain/kotlin/util/GenerateImageLoader.kt
  client_restaurant/shared/src/commonMain/resources/cuisine_placeholder.png
  client_restaurant/shared/src/commonMain/resources/meal_error_placeholder_dark.jpg
  client_restaurant/shared/src/commonMain/resources/meal_error_placeholder_light.jpg
  client_restaurant/shared/src/commonMain/resources/restaurant_error.png
  client_restaurant/shared/src/commonMain/resources/restaurant_error_dark.jpg
  design_system/shared/build.gradle.kts
  design_system/shared/src/commonMain/kotlin/ui/composable/BpImageLoader.kt
Labels: enhancement

#600 feature/map-calculate-time-and-distance
  client_delivery/androidApp/src/androidMain/assets/bing_map/map/index.html
  client_delivery/androidApp/src/androidMain/assets/bing_map/map/logo-respircov.png
  client_delivery/androidApp/src/androidMain/assets/bing_map/map/script.js
  client_delivery/androidApp/src/androidMain/assets/bing_map/map/style.css
  client_delivery/shared/src/commonMain/kotlin/domain/usecase/ManageOrderUseCase.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/MapScreen.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/MapScreenModel.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/MapScreenUiState.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/composable/AcceptedOrderCard.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/composable/DistanceInfo.kt
  client_delivery/shared/src/commonMain/kotlin/presentation/map/composable/MapView.kt
  client_delivery/shared/src/commonMain/resources/current_location.svg
  client_delivery/shared/src/commonMain/resources/restaurant_location.svg
Labels: bug, enhancement

#602 fix/ui
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/login/LoginScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/login/LoginScreenInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/login/LoginScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registration/RegistrationInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registration/RegistrationScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registration/RegistrationScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registrationSubmit/RegistrationSubmitInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registrationSubmit/RegistrationSubmitScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/auth/signup/registrationSubmit/RegistrationSubmitScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/BpImageCard.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/MealBottomSheet.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/composable/ToastMessage.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreenInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/home/HomeScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/meals/MealsInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/meals/MealsScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/meals/MealsScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/Composable/NeedToLoginSheet.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/RestaurantInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/RestaurantScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/RestaurantScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/ResturantUIState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/search/SearchInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/search/SearchScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/search/SearchScreenModel.kt
  design_system/shared/src/commonMain/kotlin/ui/composable/BPSnackBar.kt
Labels: bug

#603 fix ios restaurant and enduser
  client_end_user/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  client_end_user/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/app-icon-1024.png
  client_end_user/iosApp/iosApp/Preview Content/Preview Assets.xcassets/1670322289884_test.imageset/Contents.json
  client_end_user/iosApp/iosApp/iOSApp.swift
  client_end_user/shared/build.gradle.kts
  client_end_user/shared/src/iosMain/kotlin/FireBaseMessageService.kt
  client_restaurant/iosApp/iosApp/iOSApp.swift
  client_restaurant/shared/src/commonMain/kotlin/data/gateway/remote/IdentityRemoteGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/gateway/remote/IIdentityRemoteGateway.kt
  client_restaurant/shared/src/commonMain/kotlin/domain/usecase/LoginUserUseCase.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/information/RestaurantInformationScreen.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/main/MainScreen.kt
  client_restaurant/shared/src/commonMain/kotlin/presentation/restaurantSelection/RestaurantSelectionScreen.kt
  client_restaurant/shared/src/iosMain/kotlin/main.ios.kt
  client_restaurant/shared/src/iosMain/kotlin/util/PlatformUtil.kt
Labels: bug

#605 Fix/end user/track order on map
  client_delivery/shared/src/commonMain/kotlin/presentation/map/composable/MapView.kt
  client_delivery/shared/src/commonMain/kotlin/resources/DrawableResources.kt
  client_end_user/androidApp/src/androidMain/assets/bing_map/map/index.html
  client_end_user/androidApp/src/androidMain/assets/bing_map/map/script.js
  client_end_user/androidApp/src/androidMain/assets/bing_map/map/style.css
  client_end_user/shared/src/commonMain/kotlin/presentation/orderFoodTracking/OrderFoodTrackingScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/orderFoodTracking/composables/MapView.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/taxi/TaxiOrderScreen.kt
Labels: bug, enhancement

#607 DesignCart Dialog | Clear Cart Endpoint
  api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/RestaurantService.kt
  api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/CartRoute.kt
  client_end_user/shared/src/commonMain/kotlin/data/gateway/fake/FakeChatGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/gateway/fake/FakeTransactionsGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/gateway/remote/BaseGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/gateway/remote/RestaurantGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/gateway/remote/TransactionsGateway.kt
  client_end_user/shared/src/commonMain/kotlin/data/gateway/remote/UserGateway.kt
  client_end_user/shared/src/commonMain/kotlin/domain/gateway/ITransactionsGateway.kt
  client_end_user/shared/src/commonMain/kotlin/domain/usecase/CartUseCase.kt
  client_end_user/shared/src/commonMain/kotlin/domain/utils/ErrorType.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/base/BaseScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/base/ErrorState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cart/CartInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cart/CartScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cart/CartScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/cart/CartUiState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/Composable/WarningCartIsFullSheet.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/RestaurantInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/RestaurantScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/RestaurantScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/RestaurantUIEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/resturantDetails/ResturantUIState.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/search/SearchInteractionListener.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/search/SearchScreen.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/search/SearchScreenModel.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/search/SearchUiEffect.kt
  client_end_user/shared/src/commonMain/kotlin/presentation/search/SearchUiState.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/IStringResources.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/Arabic.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicEG.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicIQ.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicPS.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/ar/ArabicSY.kt
  client_end_user/shared/src/commonMain/kotlin/resources/strings/en/English.kt
  design_system/shared/src/commonMain/kotlin/ui/composable/BpTextButton.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/api/endpoints/CartRoutes.kt
  service_restaurant/src/main/kotlin/org/thechance/service_restaurant/domain/usecase/MangeCartUseCase.kt
Labels: feature
